name: Run sweekt-gradle bot

on:
  push:
    branches: ['**/*']
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  run:
    if: "!startsWith(github.event.head_commit.message, 'release: ')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to specify a token here, because the default "GITHUB_TOKEN"
          # will not trigger a "push" event.
          token: ${{ secrets.BOT_TOKEN }}
          # Avoid "fatal: refusing to merge unrelated histories"
          fetch-depth: 0

      - uses: ./.github/workflows/bot
        env:
          GITHUB_CLIENT_TOKEN: ${{ secrets.BOT_TOKEN }}
